export enum AppRoutes {
  home = '/home',
  wallet = '/wallet',
  my_orders = '/my-orders',
  shop = '/home/shop',
  search = '/home/search',
  visit = 'visit',
  team_up = 'team-up',
  talk = 'talk',
  settings = 'settings',
  page_404 = 'page-404',
  callback = '/callback/:version/:type/:provider',
  auth = '/auth/:type',
  authSignIn = '/auth/signin',
  authSignUp = '/auth/signup',
  cart = '/home/cart',
  discover = '/home/discover',
  compete = '/home/compete',
  helpAndSupport = '/home/help-and-support',
  privacyPolicy = '/home/privacy-policy',
  termsAndConditions = '/home/terms-and-conditions',
  chat = '/home/chat',
  shopMain = '/shop'
}
