export type ContentModel = {
    id: string,
    img?: string,
    title: string,
    type?: string,
    number_of_likes?: number,
    description?: string,
    is_official_account?: number,
    breadcrumbs?: Array<string>,
    snapshot?: string,
    views?: number,
    likes?: number,
    desc?: string,
    islive?: boolean,
    total_followers?: number,
    game_code?: string,
    combination_id?: number,
    viewer_is_self_user?: number,
    viewer_is_following?: number,
    grand_total?: number,
    total_price?: number,
    product_rating?: number,
    total_raters?: number,
    pagination?: string
}
